# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: true

addons:
  apt:
    packages:
      - libgsl-dev
      - libgsl0-dev
      - libcurl4-openssl-dev
      - libopenblas-dev
